### ISSUE TITLE
解密的db文件后是mac微信的聊天记录而非iphone备份的聊天记录？

### ISSUE THREAD

**Issue by uQingTao** [allen1881996/WeChat-Data-Analysis#1]
1. `~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/com.tencent.xinWeChat/*/*/Message/*.db`
此目录下的db文件获取的信息和微信mac版里的聊天记录对应。假如mac微信是最新安装的，登陆后实际并没有几条聊天记录。iphone中的聊天记录备份（微信自带的备份功能）到mac后，微信mac版里也不会有聊天内容。
2. iphone通过itunes备份后路径：`~/资源库 /Application Support/MobileSync/Backup/`我看您的方法介绍里并没有涉及到此路径里的内容。

**通过上面的方法，我只能查到mac微信里的聊天内容而非iphone的备份，请问是否如此？如有错误请指教。**

**Comment by allen1881996** [comment]
本地数据库储存的确实是mac微信的聊天记录，所以你需要现同步iphone和你的macbook。在步骤“微信聊天记录备份与导出”里面按照要求备份就可以了。

**Comment by allen1881996** [comment]
> 1. `~/Library/Containers/com.tencent.xinWeChat/Data/Library/Application\ Support/com.tencent.xinWeChat/*/*/Message/*.db`
>    此目录下的db文件获取的信息和微信mac版里的聊天记录对应。假如mac微信是最新安装的，登陆后实际并没有几条聊天记录。iphone中的聊天记录备份（微信自带的备份功能）到mac后，微信mac版里也不会有聊天内容。
> 2. iphone通过itunes备份后路径：`~/资源库 /Application Support/MobileSync/Backup/`我看您的方法介绍里并没有涉及到此路径里的内容。
> 
> **通过上面的方法，我只能查到mac微信里的聊天内容而非iphone的备份，请问是否如此？如有错误请指教。**

本地数据库储存的确实是mac微信的聊天记录，所以你需要现同步iphone和你的macbook。在步骤“微信聊天记录备份与导出”里面按照要求备份就可以了。
