### ISSUE TITLE
按照步骤流程，但读取 不了rsi寄存器内容

### ISSUE THREAD

**Issue by sbitpdc** [allen1881996/WeChat-Data-Analysis#6]
每一步都按照这些流程做了，但当读取 rsi 寄存器内容时候出错，
执行命令：memory read –s 1 -f x -c 32 $rsi
出错如下：
error: Process is running.  Use 'process interrupt' to pause execution.

怀疑可能是最新版本，登录时候不会进入断点，打了断点无效，会直接登录成功

**Comment by CandyClass** [comment]
同问题。你有什么解决办法吗？

**Comment by sbitpdc** [comment]
> 同问题。你有什么解决办法吗？

没有解决办法，刚接触这个工具，也不太了解具体原理。按理来说，打了断点，那么执行到这一步，就会卡住。但感觉断点打错了，跳过了打的断点，估计新版微信自己重新写了库

**Comment by sbitpdc** [comment]
> 同问题。你有什么解决办法吗？

已经解决了，用旧版本的微信
